# Generated by Django 3.0.6 on 2020-05-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_Image', models.ImageField(upload_to='images/')),
                ('image_Text', models.CharField(max_length=1000)),
            ],
        ),
    ]
